export const gyorsitok = [
  {
    image: '/images/gyorsitok/piros.png',
    color: 'piros',
    desc: '2 körön át 1,5 sebzés.',
    cost: 6,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/narancssarga.png',
    color: 'narancssárga',
    desc: '2 körön át 0,5 sebzés (az ellenfélnek).',
    cost: 6,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/vilagoskek.png',
    color: 'világoskék',
    desc: 'a következő körben minden kártyád energia költsége eggyel csökken.',
    cost: 2,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/kek.png',
    color: 'kék',
    desc: '+ 4 energia a következő körben.',
    cost: 2,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/fekete.png',
    color: 'fekete',
    desc: 'A következő körben immunis vagy minden támadásra.',
    cost: 7,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/zold.png',
    color: 'zöld',
    desc: 'Az ellenfél előző körben kijátszott kártyái közül választhatsz egyet, aminek a hatása megfordul.',
    cost: 8,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/lila.png',
    color: 'lila',
    desc: 'A következő körben az ellenfeled - 3 energiával kezd.',
    cost: 2,
    qty: 2,
  },
  {
    image: '/images/gyorsitok/feher.png',
    color: 'fehér',
    desc: '1,5x sebzés egy kártyára (amit választunk az adott körben), hogy ha az ellenfélnek van pajzsa akkor nem történik semmi, az ellenfél kivédheti ezt a támadást a következő körben pajzzsal.',
    cost: 2,
    qty: 2,
  },
];
